package View;

import Model.SpectacolOperations;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class AdminView extends JFrame {
    private JPanel panel1;
    private JScrollPane scrollPane1;
    private JTable tabelSpectacole;
    private JTextField idSpectacolField;
    private JTextField genField;
    private JTextField titluField;
    private JButton adaugaSpectacolButton;
    private JButton modificaSpectacolButton;
    private JScrollPane scrollPane2;
    private JTable tabelCasieri;
    private JTextField numeField;
    private JTextField idCasierField;
    private JTextField usernameField;
    private JTextField parolaField;
    private JButton adaugaCasierButton;
    private JButton logOutButton;
    private JTextField regiaField;
    private JTextField dataField;
    private JButton modificaDateCasierButton;
    private JTextField bileteField;
    private JTextField distributiaField;
    private MyModel modelSpectacol;
    private String[] selectedData;
    private ListSelectionModel listSelectionModelSpectacol;


    public AdminView() {

        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        modelSpectacol = new MyModel();
        tabelSpectacole = new JTable();
        listSelectionModelSpectacol = tabelSpectacole.getSelectionModel();
        tabelSpectacole.setSelectionModel(listSelectionModelSpectacol);
        listSelectionModelSpectacol.addListSelectionListener(new SharedListSelectionHandlerSpectacol());
        tabelSpectacole.setSelectionModel(listSelectionModelSpectacol);
        $$$setupUI$$$();

        this.setSize(1200, 1000);
        this.setLocationRelativeTo(null);
        this.setContentPane(panel1);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        modelSpectacol = new MyModel();
        tabelSpectacole = new JTable();
        listSelectionModelSpectacol = tabelSpectacole.getSelectionModel();
        tabelSpectacole.setSelectionModel(listSelectionModelSpectacol);
        listSelectionModelSpectacol.addListSelectionListener(new SharedListSelectionHandlerSpectacol());
        tabelSpectacole.setSelectionModel(listSelectionModelSpectacol);
        modelUpdate();
        tabelSpectacole.setModel(modelSpectacol);
        tabelSpectacole.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tabelSpectacole.add(tabelSpectacole.getTableHeader(), BorderLayout.PAGE_START);

        scrollPane1 = new JScrollPane(tabelSpectacole);
    }

    public void modelUpdate() {
        String[] columnNames = {"Id", "Gen", "Titlu", "Regia", "Distributia", "Data", "Total bilete", "Bilete vandute"};


        SpectacolOperations spectacolOperations = new SpectacolOperations();
        ArrayList<String[]> date = new ArrayList<String[]>();
        date = spectacolOperations.afiseazaSpectacole();

        modelSpectacol.setColumnNames(columnNames);
        modelSpectacol.setList(date);

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 2, new Insets(20, 10, 20, 10), -1, -1));
        panel2.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(550, 1400), new Dimension(2000, 2000), 0, false));
        panel1.add(scrollPane1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setViewportView(tabelSpectacole);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(16, 1, new Insets(50, 10, 0, 0), -1, 5));
        panel1.add(panel3, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        idSpectacolField = new JTextField();
        idSpectacolField.setEditable(false);
        idSpectacolField.setText("");
        panel3.add(idSpectacolField, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("ID spectacol");
        panel3.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Gen");
        panel3.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        genField = new JTextField();
        panel3.add(genField, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Titlu");
        panel3.add(label3, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        titluField = new JTextField();
        panel3.add(titluField, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        adaugaSpectacolButton = new JButton();
        adaugaSpectacolButton.setText("Adauga spectacol");
        panel3.add(adaugaSpectacolButton, new GridConstraints(14, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        modificaSpectacolButton = new JButton();
        modificaSpectacolButton.setText("Modifica date spectacol");
        panel3.add(modificaSpectacolButton, new GridConstraints(15, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Regia");
        panel3.add(label4, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        regiaField = new JTextField();
        regiaField.setText("");
        panel3.add(regiaField, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Distributia");
        panel3.add(label5, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        distributiaField = new JTextField();
        panel3.add(distributiaField, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("Data premiera");
        panel3.add(label6, new GridConstraints(10, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        dataField = new JTextField();
        panel3.add(dataField, new GridConstraints(11, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label7 = new JLabel();
        label7.setText("Bilete");
        panel3.add(label7, new GridConstraints(12, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        bileteField = new JTextField();
        panel3.add(bileteField, new GridConstraints(13, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        scrollPane2 = new JScrollPane();
        panel1.add(scrollPane2, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tabelCasieri = new JTable();
        scrollPane2.setViewportView(tabelCasieri);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel4, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridLayoutManager(10, 1, new Insets(40, 10, 0, 0), -1, -1));
        panel4.add(panel5, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        numeField = new JTextField();
        panel5.add(numeField, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label8 = new JLabel();
        label8.setText("Nume");
        panel5.add(label8, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label9 = new JLabel();
        label9.setText("ID casier");
        panel5.add(label9, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        idCasierField = new JTextField();
        idCasierField.setEditable(false);
        idCasierField.setText("");
        panel5.add(idCasierField, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label10 = new JLabel();
        label10.setText("Username");
        panel5.add(label10, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        usernameField = new JTextField();
        usernameField.setEditable(true);
        panel5.add(usernameField, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        parolaField = new JTextField();
        parolaField.setEditable(true);
        panel5.add(parolaField, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        adaugaCasierButton = new JButton();
        adaugaCasierButton.setText("Adauga casier");
        panel5.add(adaugaCasierButton, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label11 = new JLabel();
        label11.setText("Parola");
        panel5.add(label11, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        modificaDateCasierButton = new JButton();
        modificaDateCasierButton.setText("Modifica date casier");
        panel5.add(modificaDateCasierButton, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 20, 0), -1, -1));
        panel1.add(panel6, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        logOutButton = new JButton();
        logOutButton.setText("Log Out");
        panel6.add(logOutButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    class SharedListSelectionHandlerSpectacol implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent e) {
            ListSelectionModel lsm = (ListSelectionModel) e.getSource();
            if (tabelSpectacole.getSelectedRow() != -1) {
                idSpectacolField.setText(tabelSpectacole.getValueAt(tabelSpectacole.getSelectedRow(), 0).toString());
                genField.setText(tabelSpectacole.getValueAt(tabelSpectacole.getSelectedRow(), 1).toString());
                titluField.setText(tabelSpectacole.getValueAt(tabelSpectacole.getSelectedRow(), 2).toString());
                regiaField.setText(tabelSpectacole.getValueAt(tabelSpectacole.getSelectedRow(), 3).toString());
                distributiaField.setText(tabelSpectacole.getValueAt(tabelSpectacole.getSelectedRow(), 4).toString());
                dataField.setText(tabelSpectacole.getValueAt(tabelSpectacole.getSelectedRow(), 5).toString());
                bileteField.setText(tabelSpectacole.getValueAt(tabelSpectacole.getSelectedRow(), 6).toString());
            }
        }
    }

    public void setListenerAdaugaSpectacolButon(ActionListener e) {
        adaugaSpectacolButton.addActionListener(e);
    }

    public void setListenerModificaSpectacolButon(ActionListener e) {
        modificaSpectacolButton.addActionListener(e);
    }

    public void setListenerAdaugaCasierButon(ActionListener e) {
        adaugaCasierButton.addActionListener(e);
    }

    public void setListenerModificaDateCasierButon(ActionListener e) {
        modificaDateCasierButton.addActionListener(e);
    }

    public MyModel getModelSpectacol() {
        return modelSpectacol;
    }

    public JTextField getDistributiaField() {
        return distributiaField;
    }

    public void setListenerLogOutButon(ActionListener e) {
        logOutButton.addActionListener(e);
    }

    public JTable getTabelSpectacole() {
        return tabelSpectacole;
    }

    public void setTabelSpectacole(JTable tabelSpectacole) {
        this.tabelSpectacole = tabelSpectacole;
    }

    public JTextField getIdSpectacolField() {
        return idSpectacolField;
    }

    public void setIdSpectacolField(JTextField idSpectacolField) {
        this.idSpectacolField = idSpectacolField;
    }

    public JTextField getGenField() {
        return genField;
    }

    public void setGenField(JTextField genField) {
        this.genField = genField;
    }

    public JTextField getTitluField() {
        return titluField;
    }

    public void setTitluField(JTextField titluField) {
        this.titluField = titluField;
    }

    public JTable getTabelCasieri() {
        return tabelCasieri;
    }

    public void setTabelCasieri(JTable tabelCasieri) {
        this.tabelCasieri = tabelCasieri;
    }

    public JTextField getNumeField() {
        return numeField;
    }

    public void setNumeField(JTextField numeField) {
        this.numeField = numeField;
    }

    public JTextField getIdCasierField() {
        return idCasierField;
    }

    public void setIdCasierField(JTextField idCasierField) {
        this.idCasierField = idCasierField;
    }

    public JTextField getUsernameField() {
        return usernameField;
    }

    public void setUsernameField(JTextField usernameField) {
        this.usernameField = usernameField;
    }

    public JTextField getParolaField() {
        return parolaField;
    }

    public void setParolaField(JTextField parolaField) {
        this.parolaField = parolaField;
    }

    public JTextField getRegiaField() {
        return regiaField;
    }

    public void setRegiaField(JTextField regiaField) {
        this.regiaField = regiaField;
    }

    public JTextField getDataField() {
        return dataField;
    }

    public void setDataField(JTextField dataField) {
        this.dataField = dataField;
    }

    public JTextField getBileteField() {
        return bileteField;
    }

    public void setBileteField(JTextField bileteField) {
        this.bileteField = bileteField;
    }


}

